# Generated by Django 3.2.8 on 2021-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('periodo', models.DateField()),
                ('situacao', models.CharField(max_length=100, verbose_name='Situacao')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'verbose_name': 'Situacao',
                'verbose_name_plural': 'Situacoes',
            },
        ),
    ]
