# Generated by Django 3.2.8 on 2021-10-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211013_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheacao',
            name='status',
            field=models.CharField(choices=[('andamento', 'Andamento'), ('concluido', 'Concluído')], default='Andamento', max_length=100, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
