# Generated by Django 3.2.8 on 2021-10-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detalheacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
    ]
