# Generated by Django 3.2.8 on 2021-10-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_situacao_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='detalheacao',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('andamento', 'Andamento')], max_length=100, verbose_name='Status'),
        ),
    ]
