# Generated by Django 3.2.8 on 2021-10-14 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211013_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='causas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.causa'),
        ),
        migrations.AlterField(
            model_name='causa',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.situacao'),
        ),
        migrations.AlterField(
            model_name='detalheacao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acao'),
        ),
    ]
