# Generated by Django 3.2.8 on 2021-10-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211013_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Valor'),
        ),
    ]
