# Generated by Django 3.2.8 on 2021-10-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_detalheacao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalheacao',
            name='data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='detalheacao',
            name='status',
            field=models.CharField(choices=[('andamento', 'Andamento'), ('concluido', 'Concluído')], max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='detalheacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
    ]
