# Generated by Django 3.2.8 on 2021-10-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211013_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheacao',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='detalheacao',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('andamento', 'Andamento')], max_length=100, verbose_name='Status'),
        ),
    ]
