# Generated by Django 3.2.8 on 2021-10-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211013_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheacao',
            name='status',
            field=models.CharField(choices=[('concluido', 'Concluído'), ('andamento', 'Andamento')], default='Andamento', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='detalheacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor'),
        ),
    ]
