# Generated by Django 3.2.8 on 2021-10-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211013_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheacao',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Andamento', 'Andamento')], default='Andamento', max_length=100, verbose_name='Status'),
        ),
    ]
