# Generated by Django 3.2.8 on 2021-10-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_detalheacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheacao',
            name='status',
            field=models.CharField(choices=[('Andamento', 'Andamento'), ('Concluído', 'Concluído')], default='Andamento', max_length=100, verbose_name='Status'),
        ),
    ]
